# Variables
CFLAGS := "-Wall -Wextra -O2"
SRC := "main.c variable.c"
OUT := "main.out"

# Build rule
build:
    @gcc {{SRC}} -o {{OUT}} {{CFLAGS}}

# Run rule
run:
    @./{{OUT}} + just clean

# Build + Run + Clean together
br:
    @just build && just run && just clean

# Remove built binary
clean:
    @rm {{OUT}}
